version: "3"

volumes:
  drive:
    driver: local
  record:
    driver: local

services:
  guacd:
    extends:
      file: common-services.yml
      service: guacd

  server:
    extends:
      file: common-services.yml
      service: server
    ports:
      - 8080:8080

  webdav:
    extends:
      file: common-services.yml
      service: webdav

  client:
    extends:
      file: common-services.yml
      service: client
    ports:
      - 443:443
